### ISSUE TITLE
The lib doesn't handle `AuthenticationClient`

### ISSUE THREAD

**Issue by Anisi** [hoangnguyen1247/nestjs-auth0-management#7]
Hello
By `InjectManagementClient` only access to `ManagementClient` methods is guaranteed.
What should we do to access `AuthenticationClient` methods?

**Comment by hoangnguyen1247** [comment]
Hi @Anisi you can find guide on README.md

**Comment by Anisi** [comment]
Thank you @hoangnguyen1247 
Let me explain the problem in detail:
This is my service code:
```ts
import { ManagementClient, AuthenticationClient } from 'auth0';

... 

@Injectable()
export class UserService {
  constructor(
    @InjectManagementClient()
    private readonly auth0ManagementClient: ManagementClient,
    @InjectManagementClient()
    private readonly auth0AuthClient: AuthenticationClient,
  ) {}

...

update(id: string, updateUserDto: UpdateUserDto) {
  return this.auth0AuthClient.changePassword({
    email: 'test@test.com',
    password: 'newPassword',
    connection: 'Username-Password-Authentication',
  });
}

```
After calling the related endpoint to `update` of service, it raises this exception:
TypeError: this.auth0AuthClient.changePassword is not a function.
But it works for `ManagementClient` collection properly.

**Comment by hoangnguyen1247** [comment]
@Anisi Using this one https://github.com/hoangnguyen1247/nestjs-auth0 for `AuthenticationClient `.
